# Generated by Django 5.1.7 on 2025-03-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscore',
            name='crop_yield_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='crop_yield_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='land_quality_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='land_quality_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='market_demand_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='market_demand_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='sustainability_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='sustainability_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='weather_risk_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='weather_risk_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditscoreparameter',
            name='parameter_type',
            field=models.CharField(choices=[('land_quality', 'Land Quality'), ('weather_risk', 'Weather Risk'), ('crop_yield', 'Crop Yield'), ('market_demand', 'Market Demand'), ('sustainability', 'Sustainability')], default='land_quality', max_length=20),
        ),
    ]
