# Generated by Django 5.1.7 on 2025-03-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0002_creditscore_crop_yield_contribution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditscore',
            name='crop_yield_contribution',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='crop_yield_score',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='land_quality_contribution',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='land_quality_score',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='market_demand_contribution',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='market_demand_score',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='sustainability_contribution',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='sustainability_score',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='weather_risk_contribution',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='weather_risk_score',
        ),
        migrations.RemoveField(
            model_name='creditscoreparameter',
            name='parameter_type',
        ),
    ]
