# Generated by Django 5.1.7 on 2025-03-23 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0003_remove_creditscore_crop_yield_contribution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditscore',
            options={},
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='model_used',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='risk_category',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='score',
        ),
        migrations.AddField(
            model_name='creditscore',
            name='crop_yield_score',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='land_quality_score',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='market_demand_score',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='sustainability_score',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='weather_risk_score',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
