# Generated by Django 5.1.7 on 2025-03-23 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_farmerprofile_full_name_and_more'),
        ('credit_score', '0004_alter_creditscore_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditscore',
            options={'ordering': ['-calculation_date']},
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmerprofile'),
        ),
    ]
