# Generated by Django 5.1.7 on 2025-03-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_farmerprofile_full_name_farmerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
