# Generated by Django 5.1.7 on 2025-03-22 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField(blank=True, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=50, null=True)),
                ('irrigation_source', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmlands', to='accounts.farmerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CropHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('planting_date', models.DateField()),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('yield_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Yield in quintals', max_digits=10, null=True)),
                ('yield_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per quintal in INR', max_digits=10, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_of_production', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_history', to='gis_data.farmland')),
            ],
            options={
                'verbose_name_plural': 'Crop histories',
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteImagery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_date', models.DateField()),
                ('image_url', models.URLField()),
                ('image_type', models.CharField(choices=[('rgb', 'RGB'), ('ndvi', 'NDVI - Vegetation Index'), ('evi', 'EVI - Enhanced Vegetation Index'), ('moisture', 'Soil Moisture'), ('other', 'Other')], max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_imagery', to='gis_data.farmland')),
            ],
            options={
                'verbose_name_plural': 'Satellite imagery',
                'ordering': ['-image_date'],
            },
        ),
        migrations.CreateModel(
            name='SoilHealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nitrogen', models.DecimalField(blank=True, decimal_places=2, help_text='Nitrogen in kg/ha', max_digits=6, null=True)),
                ('phosphorus', models.DecimalField(blank=True, decimal_places=2, help_text='Phosphorus in kg/ha', max_digits=6, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, help_text='Potassium in kg/ha', max_digits=6, null=True)),
                ('organic_matter', models.DecimalField(blank=True, decimal_places=2, help_text='Organic matter in percentage', max_digits=5, null=True)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, help_text='Moisture content in percentage', max_digits=5, null=True)),
                ('soil_health_index', models.DecimalField(blank=True, decimal_places=2, help_text='Overall soil health index (0-100)', max_digits=5, null=True)),
                ('test_lab', models.CharField(blank=True, max_length=100, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='soil_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_health_data', to='gis_data.farmland')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Relative humidity in percentage', max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, help_text='Rainfall in mm', max_digits=6)),
                ('wind_speed', models.DecimalField(decimal_places=2, help_text='Wind speed in km/h', max_digits=5)),
                ('source', models.CharField(help_text='Source of weather data', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='gis_data.farmland')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('farmland', 'date')},
            },
        ),
    ]
