# Generated by Django 5.1.7 on 2025-03-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_farmerprofile_full_name_and_more'),
        ('gis_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandSaleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.DecimalField(decimal_places=2, help_text='Asking price in INR', max_digits=12)),
                ('price_per_acre', models.DecimalField(decimal_places=2, help_text='Price per acre in INR', max_digits=10)),
                ('description', models.TextField(help_text='Additional details about the land')),
                ('contact_number', models.CharField(help_text='Contact number for inquiries', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmland', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_listing', to='gis_data.farmland')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_sale_listings', to='accounts.farmerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
