# Generated by Django 5.1.7 on 2025-03-22 10:07

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('loan_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-created_at']},
        ),
    ]
