# Generated by Django 5.1.7 on 2025-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_application', '0002_auto_20250322_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(choices=[('crop_loan', 'Crop Loan'), ('equipment_loan', 'Farm Equipment Loan'), ('development_loan', 'Farm Development Loan'), ('livestock_loan', 'Livestock Loan')], default='crop_loan', max_length=20),
            preserve_default=False,
        ),
    ] 