# Generated by Django 5.1.7 on 2025-03-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_application', '0003_add_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ] 