# Generated by Django 5.1.7 on 2025-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_application', '0004_add_amount_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='term',
            field=models.IntegerField(default=12, help_text='Loan term in months'),
            preserve_default=False,
        ),
    ] 