# Generated by Django 5.1.7 on 2025-03-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_application', '0007_add_updated_at_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='additional_documents',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='additional_info_requested',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='crop_plan',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_product',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='tenure_requested',
        ),
    ]
